config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'modal_dashboards#index'

  get 'modal_dashboards/index'

  post 'modal_dashboards/create_user', to: 'modal_dashboards#create_user'
  post 'modal_dashboards/create_employment', to: 'modal_dashboards#create_employment'
  get '/employment_form', to: 'modal_dashboards#employment_form'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employment.rb
class Employment < ApplicationRecord
  validates :employer_name, presence: true
  validates :employment_started_date, presence: true
  validates :employment_ended_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true, length: { maximum: 25 }
  validates :last_name, presence: true, length: { maximum: 50 }
  validates :email, presence: true
  validates :phone_number, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employments_controller.rb
class EmploymentsController < ApplicationController
end

app/controllers/modal_dashboards_controller.rb
class ModalDashboardsController < ApplicationController
  def index
  end

  def create_user
    # Create a new User object with the given parameters
    @user = User.new(user_params)

    # Attempt to save the new user record to the database
    if @user.save
      respond_to do |format|
        format.js { render json: { status: :created, message: 'Record saved successfully', user: @user } }
      end
    else
      respond_to do |format|
        format.js { render json: { status: :unprocessable_entity, errors: @user.errors } }
      end
    end
  end

  def create_employment
    @employment = Employment.new(employment_params)
    if @employment.save
      respond_to do |format|
        format.js { render json: { status: :created, message: 'Record saved successfully', employment: @employment } }
      end
    else
      respond_to do |format|
        format.js { render json: { status: :unprocessable_entity, errors: @employment.errors } }
      end
    end
  end

  def employment_form
    render partial: 'modal_dashboards/partials/employment_form'
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :nick_name, :email, :phone_number)
    end

    def employment_params
      params.require(:employment).permit(:employer_name, :employment_started_date, :employment_ended_date)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/employments_helper.rb
module EmploymentsHelper
end

app/helpers/modal_dashboards_helper.rb
module DashboardsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboards/index.html.slim
div[data-controller="modal-form"]
  .flex.items-center.justify-center.h-screen
    .relative.px-6.pt-4.pb-4.bg-white.shadow-xl.ring-1.ring-gray-900/5.sm:mx-auto.sm:max-w-lg.sm:rounded-lg.sm:px-10
      .max-w-md.mx-auto
        .divide-y.divide-gray-300/50
          .py-8.space-y-8.text-base.leading-7.text-gray-600
            button#personalDataModalOpenBtn.w-full.h-12.px-6.text-indigo-100.transition-colors.duration-150.bg-indigo-700.rounded-lg.focus:shadow-outline.hover:bg-indigo-800[data-action="click->modal-form#open_personal_data_modal"]
              | Personal Data
            button#employmentModalOpenBtn.w-full.h-12.px-6.text-indigo-100.transition-colors.duration-150.bg-indigo-700.rounded-lg.focus:shadow-outline.hover:bg-indigo-800[data-action="click->modal-form#open_employment_modal"]
              | Employment
  #personalDataModal.fixed.top-0.left-0.flex.items-center.justify-center.hidden.w-full.h-full.modal[data-modal-form-target="personalDataModal"]
    .absolute.w-full.h-full.bg-gray-900.opacity-50.modal-overlay[data-modal-form-target="personalDataModalOverlay"]
    .z-50.w-11/12.mx-auto.overflow-y-auto.bg-white.rounded.shadow-lg.modal-container.md:max-w-md[data-controller="form"]
      .px-4.py-2.bg-gray-300.modal-header
        h2.text-lg.font-semibold
          | Personal Data
      .p-4.modal-body
        = form_with(model: User.new, url: dashboard_create_user_path, method: :post, local: true, class: "space-y-4", id: 'user-form', data: { form_target: "userForm" }) do |form|
          div
            = form.label :first_name, class: "block font-bold text-gray-700", data: {form_target: "firstNameLabel"} do
              |  First Name
              span.text-red-500
                | *
            = form.text_field :first_name, maxlength: 25, class: "block w-full border-gray-300 rounded-md shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50", required: true, data: {form_target: "firstNameInput"}
            .invalid-feedback[data-form-target="firstNameInputError"]
          div
            = form.label :last_name, class: "block font-bold text-gray-700", data: {form_target: "lastNameLabel"} do
              |  Last Name
              span.text-red-500
                | *
            = form.text_field :last_name, maxlength: 50, class: "block w-full border-gray-300 rounded-md shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50", required: true, data: {form_target: "lastNameInput"}
            .invalid-feedback[data-form-target="lastNameInputError"]
          div
            = form.label :nick_name, class: "block font-bold text-gray-700", data: {form_target: "nickNameLabel"} do
              |  Nick Name
              span.text-red-500
                | *
            = form.text_field :nick_name, class: "block w-full border-gray-300 rounded-md shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50", data: {form_target: "nickNameInput"}
            .invalid-feedback[data-form-target="nickNameInputError"]
          div
            = form.label :email, class: "block font-bold text-gray-700", data: {form_target: "emailLabel"} do
              |  Email
              span.text-red-500
                | *
            = form.email_field :email, class: "block w-full border-gray-300 rounded-md shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50", required: true, data: {form_target: "emailInput"}
            .invalid-feedback[data-form-target="emailInputError"]
          div
            = form.label :phone, class: "block font-bold text-gray-700", data: {form_target: "phoneLabel"} do
              |  Phone Number
              span.text-red-500
                | *
            = form.telephone_field :phone, maxlength: 25, class: "block w-full border-gray-300 rounded-md shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50", required: true, data: {form_target: "phoneInput"}
            .invalid-feedback[data-form-target="phoneInputError"]
      .flex.justify-end.px-4.py-5.pt-4.modal-footer
        button#personalDataModalCloseBtn.px-4.py-2.mr-2.font-bold.text-white.bg-gray-400.rounded.hover:bg-gray-500[data-action="click->modal-form#close_personal_data_modal" type="button"]
          | Cancel
        = button_tag class:"px-4 py-2 font-bold text-white bg-blue-500 rounded hover:bg-blue-700", data: {form_target: "userFormSubmitBtn"}, type: 'submit', form: 'user-form' do
          |  Save
  #employmentModal.fixed.top-0.left-0.flex.items-center.justify-center.hidden.w-full.h-full.modal[data-modal-form-target="employmentModal"]
    .absolute.w-full.h-full.bg-gray-900.opacity-50.modal-overlay[data-modal-form-target="employmentModalOverlay"]
    .z-50.w-11/12.mx-auto.overflow-y-auto.bg-white.rounded.shadow-lg.modal-container.md:max-w-md
      .px-4.py-2.bg-gray-300.modal-header
        h2.text-lg.font-semibold
          | Employment
      .p-4.modal-body
        = form_with(model: Employment.new, url: dashboard_create_employment_path, method: :post, local: true, class: "space-y-4") do |form|
          div
            = form.label :employer_name, class: "block font-bold text-gray-700" do
              |  First Name
              span.text-red-500
                | *
            = form.text_field :employer_name, class: "block w-full border-gray-300 rounded-md shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50", required: true
          div
            = form.label :employment_started_date, class: "block font-bold text-gray-700" do
              |  First Name
              span.text-red-500
                | *
            = form.date_field :employment_started_date, class: "block w-full border-gray-300 rounded-md shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50", required: true
          div
            = form.label :employment_ended_date, class: "block font-bold text-gray-700" do
              |  First Name
              span.text-red-500
                | *
            = form.date_field :employment_ended_date, class: "block w-full border-gray-300 rounded-md shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50", required: true
      .flex.justify-end.px-4.py-5.pt-4.modal-footer
        button#employmentModalCloseBtn.px-4.py-2.mr-2.font-bold.text-white.bg-gray-400.rounded.hover:bg-gray-500[data-action="click->modal-form#close_employment_modal" type="button"]
          | Cancel
        button.px-4.py-2.font-bold.text-white.bg-blue-500.rounded.hover:bg-blue-700[type="button"]
          | Save

app/views/dashboards/test_view.html.erb
<!-- Tells Stimulus to create an instance of the controller class in modal_controller.js -->
<div data-controller="modal-form">
  <div class="flex items-center justify-center h-screen">
    <div class="relative px-6 pt-4 pb-4 bg-white shadow-xl ring-1 ring-gray-900/5 sm:mx-auto sm:max-w-lg sm:rounded-lg sm:px-10">
      <div class="max-w-md mx-auto">
        <div class="divide-y divide-gray-300/50">
          <div class="py-8 space-y-8 text-base leading-7 text-gray-600">
            <button id="personalDataModalOpenBtn" data-action="click->modal-form#open_personal_data_modal" class="w-full h-12 px-6 text-indigo-100 transition-colors duration-150 bg-indigo-700 rounded-lg focus:shadow-outline hover:bg-indigo-800">Personal Data</button>
            <button id="employmentModalOpenBtn"  data-action="click->modal-form#open_employment_modal" class="w-full h-12 px-6 text-indigo-100 transition-colors duration-150 bg-indigo-700 rounded-lg focus:shadow-outline hover:bg-indigo-800">Employment</button>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Personal Data Modal -->
  <div data-modal-form-target="personalDataModal" id="personalDataModal" class="fixed top-0 left-0 flex items-center justify-center hidden w-full h-full modal">
    <div data-modal-form-target="personalDataModalOverlay" class="absolute w-full h-full bg-gray-900 opacity-50 modal-overlay"></div>
    <div data-controller="form" class="z-50 w-11/12 mx-auto overflow-y-auto bg-white rounded shadow-lg modal-container md:max-w-md">
      <!-- Modal Header -->
      <div class="px-4 py-2 bg-gray-300 modal-header">
        <h2 class="text-lg font-semibold">Personal Data</h2>
      </div>
      <!-- Modal Body -->
      <div class="p-4 modal-body">

        <!-- Tells Stimulus to create an instance of the controller class in form_controller.js -->
        <%= form_with(model: User.new, url: dashboard_create_user_path, method: :post, local: true, class: "space-y-4", id: 'user-form', data: { form_target: "userForm" }) do |form| %>
          <!-- First Name -->
          <div>
            <%= form.label :first_name, class: "block font-bold text-gray-700", data: {form_target: "firstNameLabel"} do %>
              First Name<span class="text-red-500">*</span>
            <% end %>
            <%= form.text_field :first_name, maxlength: 25, class: "block w-full border-gray-300 rounded-md shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50", required: true, data: {form_target: "firstNameInput"} %>
            <div class="invalid-feedback" data-form-target="firstNameInputError"></div>
          </div>

          <!-- Last Name -->
          <div>
            <%= form.label :last_name, class: "block font-bold text-gray-700", data: {form_target: "lastNameLabel"} do %>
              Last Name<span class="text-red-500">*</span>
            <% end %>
            <%= form.text_field :last_name, maxlength: 50, class: "block w-full border-gray-300 rounded-md shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50", required: true, data: {form_target: "lastNameInput"} %>
            <div class="invalid-feedback" data-form-target="lastNameInputError"></div>
          </div>

          <!-- Nick Name -->
          <div>
            <%= form.label :nick_name, class: "block font-bold text-gray-700", data: {form_target: "nickNameLabel"} do %>
              Nick Name<span class="text-red-500">*</span>
            <% end %>
            <%= form.text_field :nick_name, class: "block w-full border-gray-300 rounded-md shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50", data: {form_target: "nickNameInput"} %>
            <div class="invalid-feedback" data-form-target="nickNameInputError"></div>
          </div>

          <!-- Email -->
          <div>
            <%= form.label :email, class: "block font-bold text-gray-700", data: {form_target: "emailLabel"} do %>
              Email<span class="text-red-500">*</span>
            <% end %>
            <%= form.email_field :email, class: "block w-full border-gray-300 rounded-md shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50", required: true, data: {form_target: "emailInput"} %>
            <div class="invalid-feedback" data-form-target="emailInputError"></div>
          </div>

          <!-- Phone -->
            <div>
            <%= form.label :phone, class: "block font-bold text-gray-700", data: {form_target: "phoneLabel"} do %>
              Phone Number<span class="text-red-500">*</span>
            <% end %>
            <%= form.telephone_field :phone, maxlength: 25, class: "block w-full border-gray-300 rounded-md shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50", required: true, data: {form_target: "phoneInput"} %>
            <div class="invalid-feedback" data-form-target="phoneInputError"></div>
          </div>
        <% end %>
      </div>
      <!-- Modal Footer -->
      <div class="flex justify-end px-4 py-5 pt-4 modal-footer">
        <button id="personalDataModalCloseBtn"  data-action="click->modal-form#close_personal_data_modal" type="button" class="px-4 py-2 mr-2 font-bold text-white bg-gray-400 rounded hover:bg-gray-500">Cancel</button>
        <%= button_tag class:"px-4 py-2 font-bold text-white bg-blue-500 rounded hover:bg-blue-700", data: {form_target: "userFormSubmitBtn"}, type: 'submit', form: 'user-form' do %>
          Save
        <% end %>
      </div>
    </div>
  </div>

  <!-- Employment Modal-->
  <div data-modal-form-target="employmentModal" id="employmentModal" class="fixed top-0 left-0 flex items-center justify-center hidden w-full h-full modal">
    <div data-modal-form-target="employmentModalOverlay" class="absolute w-full h-full bg-gray-900 opacity-50 modal-overlay"></div>

    <div class="z-50 w-11/12 mx-auto overflow-y-auto bg-white rounded shadow-lg modal-container md:max-w-md">
      <!-- Modal Header -->
      <div class="px-4 py-2 bg-gray-300 modal-header">
        <h2 class="text-lg font-semibold">Employment</h2>
      </div>

      <!-- Modal Body -->
      <div class="p-4 modal-body">
        <%= form_with(model: Employment.new, url: dashboard_create_employment_path, method: :post, local: true, class: "space-y-4") do |form| %>
          <!-- Employer -->
          <div>
            <%= form.label :employer_name, class: "block font-bold text-gray-700" do %>
              First Name<span class="text-red-500">*</span>
            <% end %>
            <%= form.text_field :employer_name, class: "block w-full border-gray-300 rounded-md shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50", required: true %>
          </div>

          <!-- Employement Started Date -->
          <div>
            <%= form.label :employment_started_date, class: "block font-bold text-gray-700" do %>
              First Name<span class="text-red-500">*</span>
            <% end %>
            <%= form.date_field :employment_started_date, class: "block w-full border-gray-300 rounded-md shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50", required: true %>
          </div>

          <!-- Employement Ended Date -->
          <div>
            <%= form.label :employment_ended_date, class: "block font-bold text-gray-700" do %>
              First Name<span class="text-red-500">*</span>
            <% end %>
            <%= form.date_field :employment_ended_date, class: "block w-full border-gray-300 rounded-md shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50", required: true %>
          </div>
        <% end %>
      </div>

      <!-- Modal Footer -->
      <div class="flex justify-end px-4 py-5 pt-4 modal-footer">
        <button id="employmentModalCloseBtn"  data-action="click->modal-form#close_employment_modal" type="button" class="px-4 py-2 mr-2 font-bold text-white bg-gray-400 rounded hover:bg-gray-500">Cancel</button>
        <button type="button" class="px-4 py-2 font-bold text-white bg-blue-500 rounded hover:bg-blue-700">Save</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmploymentTerminal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container flex flex-col items-center mx-auto">
      <%= yield %>
    </main>
  </body>
</html>

app/views/modal_dashboards/index.html.slim
div[data-controller="modal-form"]
  .flex.items-center.justify-center.h-screen
    .px-6.py-6.bg-white.shadow-xl.ring-2.ring-gray-900/10.sm:mx-auto.sm:max-w-lg.sm:rounded-lg.sm:px-10
      .max-w-md.mx-auto
        .py-8.space-y-8
          button#personalDataModalOpenBtn.w-full.h-12.px-6.text-white.transition-colors.duration-150.bg-indigo-700.rounded-lg.focus:shadow-outline.hover:bg-indigo-800[data-action="click->modal-form#open_personal_data_modal"]
            | Personal Data
          button#employmentModalOpenBtn.w-full.h-12.px-6.text-white.transition-colors.duration-150.bg-indigo-700.rounded-lg.focus:shadow-outline.hover:bg-indigo-800[data-action="click->modal-form#open_employment_modal"]
            | Employment
  #personalDataModal.fixed.top-0.left-0.flex.items-center.justify-center.hidden.w-full.h-full[data-modal-form-target="personalDataModal"]
    #personalDataModalOverlay.absolute.w-full.h-full.bg-gray-900.opacity-50[data-modal-form-target="personalDataModalOverlay"]
    .z-50.w-11/12.mx-auto.bg-white.rounded.shadow-lg.md:max-w-md[data-controller="form"]
      .px-4.py-4.bg-gray-300
        h2.text-lg.font-semibold
          | Personal Data
      .px-6.pt-2.pb-2.overflow-y-auto.max-h-96
        div[data-form-target="errorMessage"]
          .px-4.py-2.font-bold.text-white.bg-red-500.rounded-t
            |  Error
          .px-4.py-4.text-red-700.bg-red-100.border.border-t-0.border-red-400.rounded-b
            p
              | Record not saved
        div[data-form-target="successMessage"]
          .px-4.py-2.font-bold.text-white.bg-green-500.rounded-t
            |  Success
          .px-4.py-4.text-green-700.bg-green-100.border.border-t-0.border-green-400.rounded-b
            p
              | Record saved
        = form_with(model: User.new, url: modal_dashboards_create_user_path, method: :post, remote: true, class: "space-y-4", id: 'user-form', data: { form_target: "userForm" }) do |form|
          div
            = form.label :first_name, class: "block font-bold text-gray-700", data: {form_target: "firstNameLabel"} do
              |  First Name
              span.text-red-500
                | *
            = form.text_field :first_name, maxlength: 25, class: "block w-full border-gray-300 rounded-md shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50", required: true, data: {form_target: "firstNameInput"}
            .invalid-feedback[data-form-target="firstNameInputError"]
          div
            = form.label :last_name, class: "block font-bold text-gray-700", data: {form_target: "lastNameLabel"} do
              |  Last Name
              span.text-red-500
                | *
            = form.text_field :last_name, maxlength: 50, class: "block w-full border-gray-300 rounded-md shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50", required: true, data: {form_target: "lastNameInput"}
            .invalid-feedback[data-form-target="lastNameInputError"]
          div
            = form.label :nick_name, class: "block font-bold text-gray-700", data: {form_target: "nickNameLabel"} do
              |  Nick Name
              span.text-red-500
                | *
            = form.text_field :nick_name, class: "block w-full border-gray-300 rounded-md shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50", data: {form_target: "nickNameInput"}
            .invalid-feedback[data-form-target="nickNameInputError"]
          div
            = form.label :email, class: "block font-bold text-gray-700", data: {form_target: "emailLabel"} do
              |  Email
              span.text-red-500
                | *
            = form.email_field :email, class: "block w-full border-gray-300 rounded-md shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50", required: true, data: {form_target: "emailInput"}
            .invalid-feedback[data-form-target="emailInputError"]
          div
            = form.label :phone_number, class: "block font-bold text-gray-700", data: {form_target: "phoneLabel"} do
              |  Phone Number
              span.text-red-500
                | *
            = form.telephone_field :phone_number, maxlength: 25, class: "block w-full border-gray-300 rounded-md shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50", required: true, data: {form_target: "phoneInput"}
            .invalid-feedback[data-form-target="phoneInputError"]
      .flex.justify-end.px-4.pt-8.pb-4
        button#personalDataModalCloseBtn.px-4.py-2.mr-2.font-bold.text-white.bg-gray-500.rounded.hover:bg-gray-800[type="button" data-action="click->modal-form#close_personal_data_modal"]
          | Cancel
        = button_tag class:"px-4 py-2 ml-2 font-bold text-white bg-blue-500 rounded", data: {form_target: "userFormSubmitBtn"}, type: 'submit', form: 'user-form' do
          |  Save
  #employmentModal.fixed.top-0.left-0.flex.items-center.justify-center.hidden.w-full.h-full[data-modal-form-target="employmentModal" data-form-target="employmentModal" data-employment-target="employmentModal"]
    #employmentModalOverlay.absolute.w-full.h-full.bg-gray-900.opacity-50[data-modal-form-target="employmentModalOverlay" data-form-target="employmentModalOverlay"]
    .z-50.w-11/12.mx-auto.bg-white.rounded.shadow-lg.md:max-w-md[data-controller="employment"]
      .px-4.py-4.bg-gray-300
        h2.text-lg.font-semibold
          | Employment
      .px-4.py-4.overflow-y-auto.max-h-96[data-modal-form-target="modalBodysDiv" data-employment-target="modalBodysDiv"]
        div[data-employment-target="errorMessage"]
          .px-4.py-2.font-bold.text-white.bg-red-500.rounded-t
            |  Error
          .px-4.py-4.text-red-700.bg-red-100.border.border-t-0.border-red-400.rounded-b
            p
              | Record not saved
        div[data-employment-target="successMessage"]
          .px-4.py-2.font-bold.text-white.bg-green-500.rounded-t
            |  Success
          .px-4.py-4.text-green-700.bg-green-100.border.border-t-0.border-green-400.rounded-b
            p
              | Record saved
        = render partial: 'modal_dashboards/partials/employment_form'
      .flex.justify-end.px-2.pt-8.pb-4
        = button_tag class:"px-4 py-2 mr-12 font-bold text-white bg-red-400 rounded hover:bg-red-500", id: "addemploymentFieldsBtn", data: {employment_target: "addemploymentFieldsBtn", action: 'click->employment#addNewEmploymentForm'}, type: 'submit' do
          |  Add Fields
        button#employmentModalCloseBtn.px-4.py-2.mr-2.font-bold.text-white.bg-gray-500.rounded.hover:bg-gray-800[data-action="click->modal-form#close_employment_modal" type="button"]
          | Cancel
        = button_tag class:"px-4 py-2 font-bold text-white bg-blue-500 rounded", data: {employment_target: "submitAllBtn", action: 'click->employment#submitAllForms'}, type: 'submit' do
          |  Save all Records

app/views/modal_dashboards/partials/_employment_form.html.slim
.px-4.pb-4
  = form_with(model: Employment.new, url: modal_dashboards_create_employment_path, method: :post, remote: true, class: "space-y-4") do |form|
    div
      = form.label :employer_name, class: "block font-bold text-gray-700" do
        |  Employer Name
        span.text-red-500
          | *
      = form.text_field :employer_name, class: "block w-full border-gray-300 rounded-md shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50", required: true, data: { employment_target: "employerName", action: "input->employment#validateName" }
      .invalid-feedback
    div
      = form.label :employment_started_date, class: "block font-bold text-gray-700" do
        |  Start Date
        span.text-red-500
          | *
      = form.date_field :employment_started_date, class: "block w-full border-gray-300 rounded-md shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50", required: true, data: { employment_target: "startDate", action: "input->employment#validateStartDate" }
      .invalid-feedback
    div
      = form.label :employment_ended_date, class: "block font-bold text-gray-700" do
        |  End Date
        span.text-red-500
          | *
      = form.date_field :employment_ended_date, class: "block w-full border-gray-300 rounded-md shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50", required: true, data: { employment_target: "endDate", action: "input->employment#validateEndDate" }
      .invalid-feedback
hr.px-4.py-2